### ISSUE TITLE
Get an Serialze Error when use getAs function.

### ISSUE THREAD

**Issue by wpoosanguansit** [hazelcast/hazelcast-scala#22]
I do use the cache as below:

    val conf        = new ClientConfig
    val client      = (new HzClientConfig(conf)).newClient()
    val clientCache = client.getMap[String, String](cacheName)
    serialization.Defaults.register(conf.getSerializationConfig)

     clientCache.getAs[String]("key")(result => {
      result
    })

And I do get:

Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.Scala.AsyncMap$GetAsEP.mf of type scala.Function1 in instance of com.hazelcast.Scala.AsyncMap$GetAsEP

While clientCache.get("key") works fine.  Thank for any help.

**Comment by nilskp** [comment]
You are creating the client from the config *before* you register the `Defaults` serializers with the config. Try this:

```scala
import com.hazelcast.Scala._
import com.hazelcast.Scala.client._

val conf = new ClientConfig
serialization.Defaults.register(conf.getSerializationConfig)
val client = conf.newClient()
val clientCache = client.getMap[String, String](cacheName)

val result = clientCache.getAs("key")(result => result)
```

**Comment by wpoosanguansit** [comment]
Thank you.

**Comment by nilskp** [comment]
It appears you're storing either `com.tmobile.akka.remote.RemoteActor$` directly, or it's part of the object you're storing. I can't tell you which, neither can I tell you if that's your intention.

You should either remove the reference, or define a serializer for it. It appears to be an object, which is almost free to serialize, since it's identified by its type.

See more about serialization here:
https://github.com/hazelcast/hazelcast-scala/wiki/Serialization

**Comment by wpoosanguansit** [comment]
Thanks.

**Comment by nilskp** [comment]
@wpoosanguansit Just a guess, but Scala lambdas (closures really) capture scope, so `result => result` is probably defined inside an actor, or something that closes over an actor.
Try this instead:
```scala
val result = clientCache.getAs("key")(identity)
```
